<?php
/**
* Trait CarTrait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait CarTrait
{
            use \Illuminate\Database\Eloquent\SoftDeletes;
    
    public function getCasts()
    {
        $casts = parent::getCasts();
                                                        $casts['created_at'] = 'datetime';
                                                $casts['updated_at'] = 'datetime';
                                                $casts['deleted_at'] = 'datetime';
                                                            
        return $casts;
    }

    public function getTable()
    {
        return $this->table ?? 'cars';
    }

    public function getFillable()
    {
        if (!empty($this->fillable)) {
            return $this->fillable;
        }

        return [
                            'id',
                            'created_at',
                            'updated_at',
                            'deleted_at',
                            'name',
                            'has_driver',
                    ];
    }

                                        public function carWheels(): \Illuminate\Database\Eloquent\Relations\HasMany
            {
                return $this->hasMany(\App\Models\Wheel::class, 'car_id', 'id');
            }
            }
